---
name: Parámetros
locale: es
type: learning
beta: false
teacher_info: ''
language: gobstones
id_format: "%05d"
order:
- 500
- 700
- 600
- 1105
- 800
- 1104
- 900
- 1000
- 1100
- 1101
- 1102
- 1103
private: false
